vim.cmd('nnoremap <C-b> :NvimTreeToggle<CR>')
vim.cmd('nnoremap <A-Left> :tabprevious<CR>')
vim.cmd('nnoremap <A-Right> :tabnext<CR>')
vim.cmd('nnoremap <A-Down> :tabclose<CR>')
vim.cmd('nnoremap <A-Up> :tabnew<CR>')
